WITH YearlyMax AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR_DATE,
        MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR_DATE
),
E AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        SIZE_OF_COLONY,
        ID
    FROM ECOLI_DATA
)
SELECT 
    E.YEAR,
    (Y.MAXSIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM E
INNER JOIN YearlyMax Y
ON E.YEAR = Y.YEAR_DATE
ORDER BY E.YEAR ASC, YEAR_DEV ASC;
