SELECT E.YEAR , (MAX.MAXSIZE- E.SIZE_OF_COLONY)  AS "YEAR_DEV",E.ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           SIZE_OF_COLONY,
           ID
    FROM ECOLI_DATA
) E
INNER JOIN(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR_DATE,MAX(SIZE_OF_COLONY) AS "MAXSIZE"
    FROM ECOLI_DATA
    GROUP BY YEAR_DATE
) AS MAX
ON E.YEAR=MAX.YEAR_DATE
ORDER BY E.YEAR ASC, YEAR_DEV ASC;
