-- 코드를 입력하세요
SELECT R.PRODUCT_CODE, SUM(R.PRICE*R.SALES_AMOUNT) AS 'SALES'
FROM(
    SELECT P.PRODUCT_CODE,P.PRICE,O.SALES_AMOUNT
    FROM OFFLINE_SALE O
    JOIN PRODUCT P
    ON O.PRODUCT_ID=P.PRODUCT_ID
) AS R
GROUP BY R.PRODUCT_CODE
ORDER BY SALES DESC ,R.PRODUCT_CODE ASC