-- 코드를 작성해주세요
SELECT SUM(FISH_COUNT) AS 'FISH_COUNT'
FROM(
    SELECT COUNT(FISH.ID) AS 'FISH_COUNT'
    FROM FISH_INFO FISH
    INNER JOIN FISH_NAME_INFO NAME
    ON FISH.FISH_TYPE=NAME.FISH_TYPE
    GROUP BY NAME.FISH_NAME
    HAVING NAME.FISH_NAME="BASS" OR NAME.FISH_NAME="SNAPPER"
) AS RESULT


