
SELECT SUM(J.SCORE) AS SCORE ,EMP_NO,EMP_NAME,POSITION,EMAIL
FROM(
    SELECT E.EMP_NO, G.SCORE,E.EMP_NAME,E.POSITION, E.EMAIL
    FROM HR_EMPLOYEES E
    JOIN HR_GRADE G
    ON E.EMP_NO=G.EMP_NO
    WHERE YEAR=2022
)AS J
GROUP BY J.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
